import os
import openai
from openai import OpenAI
from datetime import datetime, timedelta
import pandas as pd

# Set OpenAI API key
client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY"),
)

def generate_response(prompt: str, system_message: str = "You are a financial modeling assistant.", model: str = "gpt-4", max_tokens: int = 200) -> str:
    """
    Generate a response from GPT-4 based on a given prompt and system message.
     
    Args:
        prompt (str): The user prompt to send to the model.
        system_message (str): The system message to set the context for the model.
        model (str): The model version to use (default is "gpt-4").
        max_tokens (int): The maximum number of tokens for the response.
        
    Returns:
        str: The response generated by the model.
    """
    try:
        response = client.chat.completions.create(
            messages=[
                {
                    "role": "system",
                    "content": system_message,
                },
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            model=model,
            max_tokens=max_tokens,
            stream=True,
        )
        result = ""
        for chunk in response:
            result += chunk.choices[0].delta.content or ""
        return result
    except Exception as e:
        print(f"Error: {e}")
        return ""
